### ISSUE TITLE
Implement pluggable datatypes

### ISSUE THREAD

**Issue by seriyps** [epgsql/epgsql#109]
I've found, that Elixir postgresql driver uses pluggable datatype system.
https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/types.ex
Sample plugin https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/extensions/json.ex

I think it's a great idea.

- It allows users to implement customized encode/decode rules (eg, their preferred format of datetime, JSON, decimal etc)
- Allows users to easily handle their custom/private datatypes.
- New types may be added outside of epgsql main tree.
- epgsql code may became more 'beautiful' and generic :smiley: .

**Comment by davidw** [comment]
Sounds good to me, although I would definitely include a bunch of them with the default distribution.

**Comment by seriyps** [comment]
@ElectronicRU can you edit this one https://github.com/epgsql/epgsql/wiki/pluggable_datatypes ?

**Comment by seriyps** [comment]
Things to consider:

* Type information for rows and parameters passed as `oid`: int32
* Mapping between OIDs and type information stored in `pg_type` pseudo-table. We have to have a local copy of this table to maintain OID<->Codec functions connection.
* Each(?) basic type OID have corresponding OID for array, containing this type
* Each 'CREATE TYPE' creates 2 new rows in `pg_type` (one for `my_type` itself, another for `my_type[]`)
* Previous point valid even for `enum`s. It would be good to be able to say 'decode all enums using this decoder`, as well as `decode this particular enum using this decoder`
* There are at least 3 composite types, which may contain any(?) datatype: `array`, `range` and `record`
* Date decoding algorithm depends on `integer_datetimes` parameter (see epgsql:get_parameter(C, <<"integer_datetimes">>)` and `epgsql_fdatetime.erl`, `epgsql_idatetime.erl` modules). So, codec should be aware of a value of this parameter. This parameter couldn't change during connection's lifetime according to https://www.postgresql.org/docs/current/static/protocol-flow.html#PROTOCOL-ASYNC
* Ranges. There are some built-in range types but range of any type may be created https://www.postgresql.org/docs/current/static/rangetypes.html. Each user-defined range type is added to `pg_type` and `pg_range` tables.
* Enums. Idea is the same as for ranges https://www.postgresql.org/docs/current/static/datatype-enum.html. Each user-defined enum type is added to `pg_type` and `pg_enum`
* Records. Idea is different compared to ranges and enums. Record have always the same OID, but it's binary representation contains OIDs of it's elements. This means that we should be able to recurse from decoding function and this dynamic OID lookup should be quick enough.
* Different types with the same name may be defined in different namespaces (schemas). See #118 for details.
* Type's binary representation isn't documented. One should look into postgresql source code https://git.postgresql.org/gitweb/?p=postgresql.git;a=tree;f=src/backend/utils/adt;h=44a7fd3676c68ce83fdb7c3ef0e93808995f6d22;hb=HEAD

**Comment by seriyps** [comment]
Implemented in #153
