### ISSUE TITLE
pgsql_tests: connect_test failed

### ISSUE THREAD

**Issue by matwey** [epgsql/epgsql#11]
Hi,

I am running epgsql from the recent master and try to run unit-tests. I've created clean db env using initdb and followed instructions from `test_data/test_schema.sql`

After

```
make create_testdbs
make test
```

I get:

```
module 'pgsql'
  module 'pgsql_tests'
    pgsql_tests: all_test_ (connect_test(pgsql))...*failed*
in function pgsql_tests:connect_only/2 (test/pgsql_tests.erl, line 761)
**error:{badmatch,{error,{error,fatal,<<"3D000">>,
                        <<"database \"matwey\" does not exist">>,[]}}}
```

**Comment by davidw** [comment]
I added a `create_testdbs` target that goes partway there, but having a self-contained directory with a proper config would be even better.  Is this something you could put together?

**Comment by davidw** [comment]
I had a quick look at creating a self-contained Postgres database system in a directory.... it's kind of involved:

    /usr/lib/postgresql/9.3/bin/initdb -D datadir/

But it seems that it'll also require a few other things like a server.crt file and some other stuff to run.  Then to actually use it for testing, it'll require our own version of the pg_hba.conf and maybe postgresql.conf  files.

**Comment by matwey** [comment]
Now I am using the following:

```
%check
# setup test env
initdb --locale en_GB.UTF-8 pgsql
echo "ssl = on" >> pgsql/postgresql.conf
if [[ $(perl -e 'print shift cmp shift' $(/usr/bin/pg_config --version | awk '{print $2}') "9.2") -ge 0 ]]
then
echo "ssl_ca_file = 'root.crt'" >> pgsql/postgresql.conf
fi
cp test_data/epgsql.crt pgsql/server.crt
cp test_data/epgsql.key pgsql/server.key
cp test_data/root.crt pgsql/root.crt
cp test_data/root.key pgsql/root.key
chmod 0600 pgsql/server.key
cat > pgsql/pg_hba.conf <<EOF
local   all             $USER                                   trust
host    $USER           $USER                   127.0.0.1/32    trust
host    epgsql_test_db1 $USER                   127.0.0.1/32    trust
host    epgsql_test_db1 epgsql_test             127.0.0.1/32    trust
host    epgsql_test_db1 epgsql_test_md5         127.0.0.1/32    md5
host    epgsql_test_db1 epgsql_test_cleartext   127.0.0.1/32    password
hostssl epgsql_test_db1 epgsql_test_cert        127.0.0.1/32    cert
EOF
/usr/bin/pg_ctl start -w -D $PWD/pgsql
sleep 2
# end setup test env
make create_testdbs
echo "CREATE DATABASE $USER;" | psql template1
if [[ $(perl -e 'print shift cmp shift' $(/usr/bin/pg_config --version | awk '{print $2}') "9.1") -ge 0 ]]
then
echo "CREATE EXTENSION sslinfo;" | psql epgsql_test_db1
else
psql -d epgsql_test_db1 -f $(/usr/bin/pg_config --sharedir)/contrib/sslinfo.sql
fi
make test
make dialyzer
```

**Comment by davidw** [comment]
Cool, I'll try and borrow some of that... I think this is the 'right thing' as I hate having to edit my computer's main Postgres config file just to run some tests.

**Comment by davidw** [comment]
I added some code here: https://github.com/epgsql/epgsql/tree/self-contained-pg

It doesn't work with extensions like hstore - I'm not quite sure why.  Thanks for the script, above.

**Comment by davidw** [comment]
I have merged this into devel, and all tests now pass, if you'd like to have a look.  There are instructions for running everything in the README in that branch.

**Comment by seriyps** [comment]
I guess this one may be closed?
