### ISSUE TITLE
Using localized severity in #error structures

### ISSUE THREAD

**Issue by ElectronicRU** [epgsql/epgsql#116]
Currently, we are using localized severity (S field) in #error.severity. It would be appropriate to use symbolic severity (V field) instead, as to not depend on connection locale.

**Comment by seriyps** [comment]
This was implemented in #113, but not yet merged to master and not tagged as a release.

But it will be available not as `#error.severity`, but as `proplists:get_value(severity_en, Error#error.extra)`.

**Comment by ElectronicRU** [comment]
I do not understand why I would wish to have wrongly decoded from utf-8 atoms as a structure field. Could we switch those two around?

**Comment by seriyps** [comment]
Maybe because, according to docs, `V` field only available in Postgresql >= 9.6 ?

Fixing wrong utf8 decoding would be nice, but it's not so easy to implement to_lower for utf8 strings..

**Comment by ElectronicRU** [comment]
Then I would suggest implementing V filed support falling back on the S field. If I do a pull request in a day or so, would that be ok?

**Comment by seriyps** [comment]
Yep. Sounds like a good idea.
I don't think this will break backward compatibility, because it's unlikely that somebody uses "wrongly decoded utf8 atoms" in their apps.

**Comment by ElectronicRU** [comment]
I say if they do, they deserve it. :P

**Comment by seriyps** [comment]
Fixed by #117
