### ISSUE TITLE
Maps for hstore data

### ISSUE THREAD

**Issue by Licenser** [epgsql/epgsql#123]
I was wondering, would be be good to decode maps to hstore data in addition to the k/v lists currently used?

**Comment by seriyps** [comment]
Do you mean to accept maps as input for hstore datatype? _Encode_ instead of _decode_?
But it's unlikely that we can _decode_ hstore to maps, since it breaks backward compatibility.
BTW, if I or somebody else will do #109, all this will become irrelevant...

**Comment by Licenser** [comment]
you are totally right, this is superseded by #109 didn't made the connection when writing this.
