### ISSUE TITLE
any() query returns no results when the array contains more than one element

### ISSUE THREAD

**Issue by ruttenberg** [epgsql/epgsql#132]
Query:   "select tl_domain_name, score from tbl_tl_domain_test where tl_domain_name = any (array[$1])"

equery(Connection, Query, [["lrbears.com"]]) returns 1 row.

equery(Connection, Query, [["lrbears.com", "cnn.com"]]) returns no rows.

I think this is a bug.

**Comment by seriyps** [comment]
Sorry, didn't noticed your question.

You should use different syntax for such queries - inner `ARRAY[]` isn't needed:

```erlang
16> rp(epgsql:equery(C, "SELECT staattnum FROM pg_statistic WHERE staattnum = ANY($1)", [[1, 2]])).                                      {ok,[{column,<<"staattnum">>,int2,2,-1,1}],
    [{1},
     {1},
     {1},
     {1},
     {1},
<..>
     {2},
     {2},
     {2},
     {2},
     {2},
     {2}]}
ok

```

You may also add explicit typecasting:

```erlang
rp(epgsql:equery(C, "SELECT tmplname FROM pg_pltemplate WHERE tmplname = ANY($1::text[]::name[])", [[<<"pltcl">>, <<"plperl">>, <<"missing">>]])).
{ok,[{column,<<"tmplname">>,name,64,-1,0}],
    [{<<"pltcl">>},{<<"plperl">>}]}
```

**Comment by ruttenberg** [comment]
Thanks. Your suggested change did not solve the problem. Here is some more info:

From psql:   
select domain, score from tbl_domain_ratings where score = ANY(array[72, 54]) limit 5;
          domain           | score 
---------------------------+-------
 thoughtsonthedead.com     |    72
 northampton-news-hp.co.uk |    54
 tattooedmartha.com        |    72
 whoismgmt.com             |    72
 kelleynan.com             |    72
(5 rows)


From erlang:
Q = "select domain, score from tbl_domain_ratings where score = ANY($1) limit 5".
> epgsql:equery(Conn, Q, [72]). 
{error,{error,error,<<"22P02">>,invalid_text_representation,
              <<"array value must start with \"{\" or dimension information">>,
              [{file,<<"/home/ec2-user/padb/src/pg/src/backend/utils/adt/arrayfuncs.c">>},
               {line,<<"266">>},
               {routine,<<"array_in">>}]}}


Any thoughts?

**Comment by seriyps** [comment]
@ruttenberg you have 2 options:

1. Without type casting (type will be inherited from `score` field type
```
epgsql:equery(Conn, "select domain, score from tbl_domain_ratings where score = ANY($1) limit 5", [[72]]).
```

2. With explicit type casting (your argument is forced to be array of integers `::integer[]`)
```
epgsql:equery(Conn, "select domain, score from tbl_domain_ratings where score = ANY($1::integer[]) limit 5", [[72]]).

```

But the real issue with your code was that you passed integer `[72]`, not list of integers `[[72]]` as argument to `equery`.

**Comment by ruttenberg** [comment]
Sorry, that last message was a typo. Here is what it looks like when corrected:

epgsql:equery(Conn, Q, [[72]]). 
{error,{error,error,<<"XX000">>,internal_error,<<"Assert">>,
              [{detail,<<"\n  -----------------------------------------------\n  error:  Assert\n  co"...>>},
               {file,<<"/home/ec2-user/padb/src/sys/xen_execute.cpp">>},
               {line,<<"6624">>},
               {routine,<<"pg_throw">>}]}}

**Comment by seriyps** [comment]
@ruttenberg it looks like you use redshift as a postgresql server. As I understood, it doesn't support this postgresql feature. See https://github.com/brianc/node-postgres/issues/1186 for example.

**Comment by ruttenberg** [comment]
The example I gave you demonstrates that it is supported when using psql.

**Comment by seriyps** [comment]
@ruttenberg as you may see by link to nodejs issue, they also say that it works when array is put directly in the query and not work when passed as a parameter. I don't know postgresql internals well, but probably handling of ANY differs in those cases.

Link to comment with example: https://github.com/brianc/node-postgres/issues/1186#issuecomment-267432138

**Comment by seriyps** [comment]
@ruttenberg may you try to run your query over real (not redshift) PostgreSQL database?

**Comment by davidw** [comment]
I'd be supportive of an effort to add handling of redshift in epgsql, but that's probably worth its own issue, and branch in the code.  Someone with access would have to spearhead it, and I wouldn't want to hold back or cripple the main epgsql code in any way.

**Comment by ruttenberg** [comment]
@seriyps   The query works when done against  Postgresql 9.6.2.
My tests were with Redshift 8.0.2.
Since psql can deliver this query successfully to Redshift 8.0.2, that indicates that the over-the-wire format sent by epgsql is different from that of psql.

Do you have any plans to ensure that epgsql is Redshift compatible?

**Comment by davidw** [comment]
@ruttenberg epgsql, as an open source project, has mostly been guided by people who want to see stuff happen, and either work on it and contribute it, or hire someone to do so.

I don't think the wire protocol is different, I think you're doing the equivalent of an 'squery' with psql - maybe give squery a try, formatting the thing in a string yourself, to see if that at least lets you move forward with your project?

**Comment by ruttenberg** [comment]
@davidw 
Fair point about what psql is doing. I was probably thinking of a query with variable binding as something expanded by the client into a simple query, which may not be at all what is going on.

**Comment by davidw** [comment]
Once you've got things figured out, @ruttenberg if you'd care to write up your experiences with epgsql and Redshift, I'd be happy to add a bit of documentation, so people at least know what they're getting in to.

**Comment by ruttenberg** [comment]
@davidw   Thanks for your offer. Beyond solving my immediate problem, I don't have time to pursue further Redshift compatibility.

My workaround, which is not as clean as I would like, is to use 'in' instead of 'any'.

Thus
_"select domain, score from tbl_domain_ratings where score = ANY($1)"_
becomes
_"select domain, score from tbl_domain_ratings where score in ($1, $2, $3,...,$n)"_

This loses the advantage of having one query which will bind to a list of arbitrary size.

**Comment by seriyps** [comment]
This topic is also kind of relevant https://groups.google.com/forum/#!topic/epgsql/k5yzn8Ocfns

**Comment by ruttenberg** [comment]
@seriyps 
Thanks for the helpful link.
It turns out that Redshift doesn't support array functions, so _unnest_ is not a solution here.

**Comment by pselden** [comment]
Sorry to necro this, but is there any way to make it work with IN ($1) instead. I get no results if there is more than one entry in the list.

```erl
Ids = [<<"123">>, <<"456">>],
Results = epgsql:equery("SELECT * FROM users WHERE id IN ($1)", [Ids]).
```

**Comment by seriyps** [comment]
@pselden you may try

```
Ids = [<<"123">>, <<"456">>],
Results = epgsql:equery("SELECT * FROM users WHERE id ANY ($1::text[])", [Ids]).
```
or just
```
Ids = [<<"123">>, <<"456">>],
Results = epgsql:equery("SELECT * FROM users WHERE id ANY ($1)", [Ids]).
```

What is the type of `id` column?
