### ISSUE TITLE
Warning: ambiguous call of overridden auto-imported BIF floor/1

### ISSUE THREAD

**Issue by erltoichi** [epgsql/epgsql#134]
While trying to compile with rebar3 on Erlang OTP 20.2, I got:

> src/epgsql_fdatetime.erl:110: Warning: ambiguous call of overridden auto-imported BIF floor/1
>  - use erlang:floor/1 or "-compile({no_auto_import,[floor/1]})." to resolve name clash

Renaming the function (to epgsql_floor) in the source code makes the message disappear, but does this break anything?

**Comment by grahamrhay** [comment]
should be fixed on devel: https://github.com/epgsql/epgsql/pull/125

**Comment by erltoichi** [comment]
It seems so. It does indeed compile with the devel branch.

**Comment by seriyps** [comment]
@grahamrhay thanks!
