### ISSUE TITLE
json support

### ISSUE THREAD

**Issue by davidw** [epgsql/epgsql#14]
https://github.com/soundrop/epgsql/commit/3afda8b7200805933e7d080cc293bde24f992349 looks like a first step.

**Comment by laheadle** [comment]
@talentdeficit has a branch with tests! Is this mergeable?

https://github.com/talentdeficit/epgsql/commit/a09030d8c37edc0b70278cc88a213176411266d4

**Comment by seriyps** [comment]
@laheadle looks good. But we need also fix travis.yml to use PG 9.4 (9.3 doesn't have jsonb support).

**Comment by dxtr** [comment]
Has there been any progress on this?

**Comment by seriyps** [comment]
@davidw what do you think? May we merge patch from https://github.com/talentdeficit/epgsql/commit/a09030d8c37edc0b70278cc88a213176411266d4 ? It looks good.

**Comment by davidw** [comment]
Fixed, thanks to @talentdeficit and @seriyps - thanks guys!
