### ISSUE TITLE
Add support for PG10 scram-sha-256 auth method

### ISSUE THREAD

**Issue by seriyps** [epgsql/epgsql#142]
Recently [released PostgreSQL 10](https://www.postgresql.org/docs/10/static/release-10.html) introduces new auth method scram-sha-256. I think it would be nice to have it in epgsql.

[Most detailed description](https://www.postgresql.org/docs/current/static/sasl-authentication.html)

[Packet format](https://www.postgresql.org/docs/current/static/protocol-message-formats.html)
We are interested in:
AuthenticationSASL
AuthenticationSASLContinue
AuthenticationSASLFinal
SASLInitialResponse
SASLResponse

[Packet flow](https://www.postgresql.org/docs/current/static/protocol-flow.html#idm46046840158032)

RFCs:
[rfc7677: SCRAM-SHA-256](https://tools.ietf.org/html/rfc7677)
[rfc5802: SCRAM SASL](https://tools.ietf.org/html/rfc5802)

**Comment by seriyps** [comment]
Fixed by #156

**Comment by Neustradamus** [comment]
@seriyps: You have done a good job in 2018 :)

Can you add the SCRAM-SHA-256-PLUS too?

-------------------------

SCRAM-SHA-256 has been added in PostgreSQL 10
SCRAM-SHA-256-PLUS variant (with TLS Binding) has been added in PostgreSQL 13
SCRAM-SHA-256 is selected by default in PostgreSQL 14

History:
- 10: https://www.postgresql.org/docs/10/auth-methods.html + https://www.postgresql.org/about/news/postgresql-10-released-1786/
- 11: https://www.postgresql.org/docs/11/auth-password.html
- 12: https://www.postgresql.org/docs/12/auth-password.html
- 13: https://www.postgresql.org/docs/13/auth-password.html + https://www.postgresql.org/about/news/postgresql-13-released-2077/
- 14: https://www.postgresql.org/docs/14/auth-password.html + https://www.postgresql.org/about/news/postgresql-14-released-2318/ 

On Microsoft.com:
- https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/how-to-securely-authenticate-with-scram-in-postgres-13/ba-p/1548319

Linked to:
- https://github.com/scram-xmpp/info/issues/1
