### ISSUE TITLE
Misplaced @see into epgsql.erl

### ISSUE THREAD

**Issue by JiffB** [epgsql/epgsql#146]
Debian stable (stretch) w/ ES Erlang pkgs V.20.1-1
==========================

Hi folks, rebar3 edoc fails because epgsql.erl L49 has a misplaced '@see':

$ rebar3 edoc
===> Verifying dependencies...
===> Compiling epgsql
===> Running edoc for epgsql
/usr/local/lib/erlang/lib/epgsql/src/epgsql.erl, function connect/1: at line 49: unknown error parsing reference: {49,edoc_parser,
                                  ["syntax error before: ",["OTP"]]}.
edoc: skipping source file '/usr/local/lib/erlang/lib/epgsql/src/epgsql.erl': {'EXIT',
                                                                         error}.
edoc: error in doclet 'edoc_doclet': {'EXIT',error}.
===> Failed to generate documentation for app 'epgsql'

Once L49 '@see' is transformed to 'ATsee', it runs normally:

$ rebar3 edoc
===> Verifying dependencies...
===> Compiling epgsql
===> Running edoc for epgsql
/usr/local/lib/erlang/lib/epgsql/src/epgsql.erl: at line 58: warning: duplicated type connect_opts

**Comment by seriyps** [comment]
Hi, thanks!
Would you like to make a pull request?

**Comment by JiffB** [comment]
On Mon, 23 Oct 2017 07:57:46 +0000 (UTC)
Sergey Prokhorov <notifications@github.com> wrote:

> Hi, thanks!
> Would you like to make a pull request?
> 

Huuu, if I understand correctly, a PR is an access to the git in order
to create my own branch ?
Well, I wish I was at this level, but I know only the very basic from
git and I'm not really a programmer, much more a bricks/snippets
assembler, not to mention I'm beginning with Erlang, even if I read a
lot about it.

My goal is to write a very old project of mine, an ERP (server in 
Erlang and client in Python), but it's hard to make decisions,
especially the Erlang architecture ones, because I only used assembly, a
bit of C and C++, basic, dBaseII, dBaseIII & python before.

At this time, I'm trying to understand where to correctly implement Unix
Domain Sockets support into your epgsql, so, if I success, I may send
you a diff or the new files for review old fashion style.

So, at this time, I decline as I might much more ruin something rather
than bring something interesting to the project; but thanks anyway, that
was kind of you.

Jean-Yves

**Comment by grahamrhay** [comment]
you can actually click "edit", and github does some magic:

https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by JiffB** [comment]
On Mon, 23 Oct 2017 14:32:42 +0000 (UTC)
Graham Hay <notifications@github.com> wrote:

> you can actually click "edit", and github does some magic:
> 
> https://help.github.com/articles/editing-files-in-another-user-s-repository/
> 

Hi,

thanks for the link, but at this time I have to work to make things
cleanly (first in my own head;) - but I'll tell you when/if I'm ready.

Jean-Yves

**Comment by seriyps** [comment]
Fixed by #148
