### ISSUE TITLE
Error unnamed prepared statement does not exist

### ISSUE THREAD

**Issue by saa** [epgsql/epgsql#150]
Get error - `unnamed prepared statement does not exist`. I use cuesport as pool of epgsql connections.

**Comment by seriyps** [comment]
I looked through cuesport source code and it seems that it doesn't protect workers from concurrent access. Concurrent access works not so well for epgsql when you use `equery` or sequences of `parse -> bind -> execute` (see https://github.com/epgsql/epgsql#differences-between-current-epgsql-and-mabreks-original-async-fork).
So, I would suggest you to use a proper pool with concurrent access protection, eg, [pooler](https://github.com/seth/pooler) or poolboy

**Comment by saa** [comment]
Got it, thanks!
