### ISSUE TITLE
equery does not accept table names as parameter

### ISSUE THREAD

**Issue by loxs** [epgsql/epgsql#151]
If I do something like 

    epgsql:equery(Conn, "INSERT INTO $1 ...", [TableName] ) I get an error like:

{error,{error,error,<<"42601">>,syntax_error,
              <<"syntax error at or near \"$1\"">>,
              [{file,<<"scan.l">>},
               {line,<<"1082">>},
               {position,<<"13">>},
               {routine,<<"scanner_yyerror">>}]}}

**Comment by seriyps** [comment]
Not a bug: https://stackoverflow.com/questions/13793399/passing-table-name-as-a-parameter-in-psycopg2
