### ISSUE TITLE
crash when inserting datatype "character"

### ISSUE THREAD

**Issue by telsgaard** [epgsql/epgsql#159]
In release 3.4.0 I can insert the string "cf481049d548f05494091e5895bc312f" into an column type character (32), but after upgrading to master, i get following crash:

=ERROR REPORT==== 9-May-2018::07:40:06 ===
** Generic server <0.548.0> terminating 
** Last message in was {command,epgsql_cmd_equery,
                           {{statement,[],[],
                                [varchar,varchar,varchar,varchar,bpchar], 
                                [{1043,varchar,false},
                                 {1043,varchar,false},
                                 {1043,varchar,false},
                                 {1043,varchar,false},
                                 {1042,bpchar,false}]},
                            [{varchar,"aa1111@lab24.timezone4.com"},
                             {varchar,"VK11111114"},
                             {varchar,"aa1111@lab24.timezone4.com"},
                             {varchar,virtual},
                             {bpchar,"cf481049d548f05494091e5895bc312f"}]}}
** When Server state == {state,gen_tcp,#Port<0.932>,<<>>,
                         {69269,1770382011},
                         on_message,
                         {codec,[],
                          {oid_db,
                           #{3905 =>
                              {type,3905,int4range,true,3904,
                               epgsql_codec_intrange,[]},
                             775 =>
                              {type,775,macaddr8,true,774,epgsql_codec_net,[]},
                             2950 =>
                              {type,2950,uuid,false,undefined,
                               epgsql_codec_uuid,[]},
                             600 =>
                              {type,600,point,false,undefined,
                               epgsql_codec_geometric,[]},
                             1001 =>
                              {type,1001,bytea,true,17,epgsql_codec_text,[]},
                             1266 =>
                              {type,1266,timetz,false,undefined,
                               epgsql_codec_datetime,epgsql_idatetime},
                             199 =>
                              {type,199,json,true,114,epgsql_codec_json,[]},
                             1017 =>
                              {type,1017,point,true,600,
                               epgsql_codec_geometric,[]},
                             20 =>
                              {type,20,int8,false,undefined, 
                               epgsql_codec_integer,[]},
                             1007 =>
                              {type,1007,int4,true,23,epgsql_codec_integer,[]},
                             17 =>
                              {type,17,bytea,false,undefined,
                               epgsql_codec_text,[]},
                             25 =>
                              {type,25,text,false,undefined,
                               epgsql_codec_text,[]},
                             1022 =>
                              {type,1022,float8,true,701,epgsql_codec_float,
                               []},
                             1270 =>
                              {type,1270,timetz,true,1266,
                               epgsql_codec_datetime,epgsql_idatetime},
                             1182 =>
                              {type,1182,date,true,1082,
                               epgsql_codec_datetime,epgsql_idatetime},
                             829 =>
                              {type,829,macaddr,false,undefined,
                               epgsql_codec_net,[]},
                             1082 =>
                              {type,1082,date,false,undefined,
                               epgsql_codec_datetime,epgsql_idatetime},
                             1042 =>
                              {type,1042,bpchar,false,undefined,
                               epgsql_codec_bpchar,[]},
                             3927 =>
                              {type,3927,int8range,true,3926,
                               epgsql_codec_intrange,[]},
                             1186 =>
                              {type,1186,interval,false,undefined,
                               epgsql_codec_datetime,epgsql_idatetime},
                             1115 =>
                              {type,1115,timestamp,true,1114,
                               epgsql_codec_datetime,epgsql_idatetime},
                             2951 =>
                              {type,2951,uuid,true,2950,epgsql_codec_uuid,[]},
                             1014 =>
                              {type,1014,bpchar,true,1042,
                               epgsql_codec_bpchar,[]},
                             1183 =>
                              {type,1183,time,true,1083,
                               epgsql_codec_datetime,epgsql_idatetime},
                             651 =>
                              {type,651,cidr,true,650,epgsql_codec_net,[]},
                             3926 =>
                              {type,3926,int8range,false,undefined,
                               epgsql_codec_intrange,[]},
                             1000 =>
                              {type,1000,bool,true,16,epgsql_codec_boolean,[]},
                             1187 =>
                              {type,1187,interval,true,1186,
                               epgsql_codec_datetime,epgsql_idatetime},
                             1043 =>
                              {type,1043,varchar,false,undefined,
                               epgsql_codec_text,[]},
                             774 =>
                              {type,774,macaddr8,false,undefined,
                               epgsql_codec_net,[]},
                             3904 =>
                              {type,3904,int4range,false,undefined,
                               epgsql_codec_intrange,[]},
                             1040 =>
                              {type,1040,macaddr,true,829,epgsql_codec_net,[]},
                             3802 =>
                              {type,3802,jsonb,false,undefined,
                               epgsql_codec_json,[]},
                             1083 =>
                              {type,1083,time,false,undefined,
                               epgsql_codec_datetime,epgsql_idatetime},
                             18 =>
                              {type,18,char,false,undefined,
                               epgsql_codec_bpchar,[]},
                             1009 =>
                              {type,1009,text,true,25,epgsql_codec_text,[]},
                             701 =>
                              {type,701,float8,false,undefined,
                               epgsql_codec_float,[]},
                             114 =>
                              {type,114,json,false,undefined,
                               epgsql_codec_json,[]},
                             21 =>
                              {type,21,int2,false,undefined,
                               epgsql_codec_integer,[]},
                             650 =>
                              {type,650,cidr,false,undefined,
                               epgsql_codec_net,[]},
                             1114 =>
                              {type,1114,timestamp,false,undefined,
                               epgsql_codec_datetime,epgsql_idatetime},
                             23 =>
                              {type,23,int4,false,undefined,
                               epgsql_codec_integer,[]},
                             1015 =>
                              {type,1015,varchar,true,1043,epgsql_codec_text,
                               []},
                             1041 =>
                              {type,1041,inet,true,869,epgsql_codec_net,[]},
                             1184 =>
                              {type,1184,timestamptz,false,undefined,
                               epgsql_codec_datetime,epgsql_idatetime},
                             1021 =>
                              {type,1021,float4,true,700,epgsql_codec_float,
                               []},
                             1005 =>
                              {type,1005,int2,true,21,epgsql_codec_integer,[]},
                             1185 =>
                              {type,1185,timestamptz,true,1184,
                               epgsql_codec_datetime,epgsql_idatetime},
                             869 =>
                              {type,869,inet,false,undefined,
                               epgsql_codec_net,[]},
                             1016 =>
                              {type,1016,int8,true,20,epgsql_codec_integer,[]},
                             16 =>
                              {type,16,bool,false,undefined,
                               epgsql_codec_boolean,[]},
                             3807 =>
                              {type,3807,jsonb,true,3802,epgsql_codec_json,[]},
                             700 =>
                              {type,700,float4,false,undefined,
                               epgsql_codec_float,[]},
                             1002 =>
                              {type,1002,char,true,18,epgsql_codec_bpchar,[]}},
                           #{{float4,false} => 700,
                             {int8,false} => 20,
                             {interval,false} => 1186,
                             {timestamp,false} => 1114,
                             {macaddr8,true} => 775,
                             {inet,false} => 869,
                             {jsonb,true} => 3807,
                             {cidr,false} => 650,
                             {date,true} => 1182,
                             {time,false} => 1083,
                             {int2,true} => 1005,
                             {varchar,false} => 1043,
                             {int8range,true} => 3927,
                             {text,true} => 1009,
                             {macaddr,true} => 1040,
                             {int4,false} => 23,
                             {point,true} => 1017, 
                             {int4range,false} => 3904,
                             {macaddr,false} => 829,
                             {float8,true} => 1022,
                             {json,false} => 114,
                             {uuid,false} => 2950,
                             {date,false} => 1082,
                             {interval,true} => 1187,
                             {jsonb,false} => 3802,
                             {int8range,false} => 3926,
                             {char,true} => 1002,
                             {timetz,false} => 1266,
                             {float8,false} => 701,
                             {timestamptz,true} => 1185,
                             {bool,false} => 16,
                             {cidr,true} => 651,
                             {bpchar,false} => 1042,
                             {int4,true} => 1007,
                             {bytea,false} => 17,
                             {float4,true} => 1021,
                             {varchar,true} => 1015,
                             {text,false} => 25,
                             {inet,true} => 1041,
                             {timetz,true} => 1270,
                             {time,true} => 1183,
                             {uuid,true} => 2951,
                             {json,true} => 199,
                             {point,false} => 600,
                             {int8,true} => 1016,
                             {bool,true} => 1000,
                             {bpchar,true} => 1014,
                             {int2,false} => 21,
                             {timestamp,true} => 1115,
                             {timestamptz,false} => 1184,
                             {macaddr8,false} => 774,
                             {char,false} => 18,
                             {int4range,true} => 3905,
                             {bytea,true} => 1001}}},
                         {[],[]},
                         undefined,undefined,undefined,undefined,
                         [{<<"application_name">>,<<>>},
                          {<<"client_encoding">>,<<"UTF8">>},
                          {<<"DateStyle">>,<<"ISO, DMY">>},
                          {<<"integer_datetimes">>,<<"on">>},
                          {<<"IntervalStyle">>,<<"postgres">>},
                          {<<"is_superuser">>,<<"on">>},
                          {<<"server_encoding">>,<<"UTF8">>},
                          {<<"server_version">>,<<"9.5.12">>},
                          {<<"session_authorization">>,<<"srd">>},
                          {<<"standard_conforming_strings">>,<<"on">>},
                          {<<"TimeZone">>,<<"localtime">>}],
                         [],[],undefined,73,undefined,undefined}
** Reason for termination ==  
** {function_clause,
       [{epgsql_codec_bpchar,encode,
            ["cf481049d548f05494091e5895bc312f",bpchar,[]],
            [{file,"src/datatypes/epgsql_codec_bpchar.erl"},{line,24}]},
        {epgsql_binary,encode_value,2,
            [{file,"src/epgsql_binary.erl"},{line,236}]},
        {epgsql_wire,encode_parameter,2,
            [{file,"src/epgsql_wire.erl"},{line,249}]},
        {epgsql_wire,encode_parameters,5,
            [{file,"src/epgsql_wire.erl"},{line,231}]},
        {epgsql_cmd_equery,execute,2,
            [{file,"src/commands/epgsql_cmd_equery.erl"},{line,35}]},
        {epgsql_sock,command_exec,4,[{file,"src/epgsql_sock.erl"},{line,270}]},
        {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},
        {gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]}]}
** Client <0.547.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,169}]},
    {gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},
    {em_srd,create_user,1,[{file,"src/em_srd.erl"},{line,54}]},
    {em_manager_hss,create_ims_association,1,
                    [{file,"src/em_manager_hss.erl"},{line,155}]},
    {em_manager_hss,create_user,1,[{file,"src/em_manager_hss.erl"},{line,24}]},
    {em_events,processor,3,[{file,"src/em_events.erl"},{line,48}]}]

=CRASH REPORT==== 9-May-2018::07:40:06 ===
  crasher:
    initial call: epgsql_sock:init/1
    pid: <0.548.0>
    registered_name: []
    exception error: no function clause matching 
                     epgsql_codec_bpchar:encode("cf481049d548f05494091e5895bc312f",
                                                bpchar,[]) (src/datatypes/epgsql_codec_bpchar.erl, line 24)
      in function  epgsql_binary:encode_value/2 (src/epgsql_binary.erl, line 236)
      in call from epgsql_wire:encode_parameter/2 (src/epgsql_wire.erl, line 249)
      in call from epgsql_wire:encode_parameters/5 (src/epgsql_wire.erl, line 231)
      in call from epgsql_cmd_equery:execute/2 (src/commands/epgsql_cmd_equery.erl, line 35)
      in call from epgsql_sock:command_exec/4 (src/epgsql_sock.erl, line 270)
      in call from gen_server:try_handle_call/4 (gen_server.erl, line 636)
      in call from gen_server:handle_msg/6 (gen_server.erl, line 665)
    ancestors: [<0.547.0>]
    message_queue_len: 0
    messages: []
    links: [<0.547.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 4601
  neighbours:
    neighbour:
      pid: <0.547.0>
      registered_name: []
      initial_call: {em_events,process,3}
      current_function: {gen,do_call,4}
      ancestors: []
      message_queue_len: 0
      links: [<0.539.0>,<0.548.0>]
      trap_exit: false
      status: waiting
      heap_size: 4185
      stack_size: 21
      reductions: 870
      current_stacktrace: [{gen,do_call,4,[{file,"gen.erl"},{line,169}]},
                  {gen_server,call,3,[{file,"gen_server.erl"},{line,210}]},
                  {em_srd,create_user,1,[{file,"src/em_srd.erl"},{line,54}]},
                  {em_manager_hss,create_ims_association,1,
                                  [{file,"src/em_manager_hss.erl"},
                                   {line,155}]},
                  {em_manager_hss,create_user,1,
                                  [{file,"src/em_manager_hss.erl"},{line,24}]},
                  {em_events,processor,3,
                             [{file,"src/em_events.erl"},{line,48}]}]

**Comment by seriyps** [comment]
Hi. Yep, I can confirm that. Will to be fixed.

**Comment by seriyps** [comment]
Fix will be as easy as adding `is_list(L) -> ...` clause to `encode`
