### ISSUE TITLE
Pull-requests to epgsql are created over `master` branch by-default

### ISSUE THREAD

**Issue by seriyps** [epgsql/epgsql#167]
In epgsql we are currently do all the development in `devel` branch and then merge it to `master` when doing next release.
In our README in [Contributing](https://github.com/epgsql/epgsql#contributing) section we have recommendation to open PRs using `devel` branch, but it's a manual task and newcomers often don't notice this recommendation.

It would be nice if we could make all PRs be automatically based on correct branch.

**Comment by davidw** [comment]
I changed it to `devel` in the settings.  Let's see how that works out...

**Comment by seriyps** [comment]
Right now I see 2 ways of achieving this:

1) Change default branch to `devel` https://help.github.com/articles/setting-the-default-branch/
2) Use `master` for integration and `stable` for releases

1st one will require minimal changes, but it looks like this layout is not so common in open-source. And it seems that with this layout https://github.com/epgsql/epgsql web page will show `devel` branch, not `master`
2nd one looks more "standard" layout, but it will require bit more changes in our "workflow"

**Comment by seriyps** [comment]
> I changed it to devel in the settings.

Ah, cool. Yep, let's see. I will keep this open for some time

**Comment by UmanShahzad** [comment]
@seriyps PRs default to devel - I think you can close this.

**Comment by seriyps** [comment]
yeah, seems problem is solved now
