### ISSUE TITLE
unexpected_message

### ISSUE THREAD

**Issue by krjmelik** [epgsql/epgsql#182]
Hello. I keep getting this error (rarely, once in a month):
{unexpected_message,69,epgsql_cmd_connect,...} because epgsql_cmd_connect:handle_message/4 receives {error,важно, <<"53300">>, too_many_connections, <<"оставшиеся слоты подключений зарезервированы для подключений суперпользователя (не для репликации)">>,
                                                         [{file,<<"src\\backend\\utils\\init\\postinit.c">>},
                                                          {line,<<"718">>},
                                                          {routine, <<"InitPostgres">>}]}, 
but Stage is 'initialization' instead of 'auth' or 'maybe_auth'.

Also in this file 'auth_state' can be 'undefned' instead of 'undefined'.

**Comment by krjmelik** [comment]
I'm kinda new to this. So perhaps you should do it. And what should I do in that clause, just stop the process? Or something else?

**Comment by seriyps** [comment]
Was fixed by #183
