### ISSUE TITLE
Connecting to CockroachDB fails with error 

### ISSUE THREAD

**Issue by larshesel** [epgsql/epgsql#192]
Hi,

I'm trying to make VerneMQ support CockroachDB and my plan was to use the `epgsql` driver for that. I'm however stumbling into a problem while connecting:

```
{ok, C1} = epgsql:connect("localhost","vmq_test_user","vmq_test_password", #{database => "vmq_test_database", port => 26257}). 
** exception error: no match of right hand side value {error,<<"08P01">>}
```

This is with epgsql 4.2.1 and cockroachdb v2.1.6 - does this ring a bell? I'm able to connect using `pgsql` like this: 

```
$ psql -p 26257 -h localhost -U vmq_test_user
Password for user vmq_test_user: 
psql (11.2 (Debian 11.2-2), server 9.5.0)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256, bits: 128, compression: off)
Type "help" for help.

vmq_test_user=> 
```

Maybe you have some hints how I can debug this?

**Comment by seriyps** [comment]
Hi. Can you, please, try to connect with epgsql 3.4.0?

Also, will it work if you try to connect using epgsql 4.2.1, but add `codecs => []` option? Like `{ok, C1} = epgsql:connect("localhost","vmq_test_user","vmq_test_password", #{database => "vmq_test_database", port => 26257, codecs => []}). `?

**Comment by seriyps** [comment]
also, if you can provide full stacktrace - it might help as well. You can use smth like

```erlang
try epgsql:connect(...) of
  {ok, C} -> ok
catch Type:Reason ->
  {Type, Reason, erlang:get_stacktrace()}
end.
```

**Comment by larshesel** [comment]
Hi, thanks for the quick response.

with `codes => []`
```erlang
> epgsql:connect("localhost","vmq_test_user","vmq_test_password", #{database => "vmq_test_database", port => 26257, codecs => []}).       
{error,<<"08P01">>}
```

I'm afraid there's no exception being thrown, just `{error,<<"08P01">>}` is returned. I tried with 3.4.0 and got the same error back.

Is there something lower level function which I could trace perhaps?

**Comment by seriyps** [comment]
Some tcpdump would be perfect

**Comment by larshesel** [comment]
my cockroachdb installation secures the DB connections with TLS, and I weren't able to decode the traffic in wireshare. So I decided to try to install cockroach without TLS (insecure mode) https://www.cockroachlabs.com/docs/stable/orchestrate-a-local-cluster-with-kubernetes-insecure.html#manual. The 'funny' thing is now it actually works - so this seems to imply that perhaps there's some kind of problem in the interplay between eqgsql and crdb when TLS is used. Not sure if that helps at all, but thought it might be an interesting finding.

**Comment by larshesel** [comment]
Hi,

Tried again with the 'secure' cockroachdb installation to see if I could get it to work with TLS - and it was actually quite simple, I simply had to specify in the client that TLS should be used:

```erlang
{ok, C} = epgsql:connect("localhost","vmq_test_user","vmq_test_password", #{ssl => true, database => "vmq_test_database", port => 26257}).
```

Then it works - sorry for the noise and thank you for the help!

**Comment by seriyps** [comment]
@larshesel well, we have a test where we try to connect with invalid client certificate:

https://github.com/epgsql/epgsql/blob/46b353886338c13280eb1ca66c425d9137e38ca2/test/epgsql_SUITE.erl#L288-L307

but it's a bit different, because we do an attempt to start tls connection, but it fails.

It would be nice to try to add a test for that. Do you want to make a PR or open an issue maybe?
