### ISSUE TITLE
How to turn on/off the autocommit

### ISSUE THREAD

**Issue by abalazsik** [epgsql/epgsql#231]
Hi!
I would like to turn on and off the autocommit feature on a db connection. The documentation says I can do it with the command:
`\set AUTOCOMMIT OFF;`
If I try it with epgsql i get a syntax_error error:
```
{error,{error,error,<<"42601">>,syntax_error,
              <<"syntax error at or near \"\\\"">>,
              [{file,<<"scan.l">>},
               {line,<<"1145">>},
               {position,<<"1">>},
               {routine,<<"scanner_yyerror">>},
               {severity,<<"ERROR">>}]}}
```
Is there a way to do it?
Thanks

**Comment by seriyps** [comment]
Hi. I think this syntax `\set AUTOCOMMIT OFF;` is only valid for `psql`. For epgsql there is no similar functionality. You just have to explicitly start and end transaction with, eg,

```erlang
epgsql:squery(C, "BEGIN"),
…
epgsql:squery(C, "COMMIT")
```

or use `with_transaction`

```erlang
epgsql:with_transaction(
  fun(C) ->
   …
  end).
```

**Comment by abalazsik** [comment]
Ok, this will work. Thank you for the help!
