### ISSUE TITLE
Can support IPV6？

### ISSUE THREAD

**Issue by wwhai** [epgsql/epgsql#234]
# Hello ，can support ipv6 network？

**Comment by seriyps** [comment]
Well, it works already if you'll just pass an IP address:

```erlang
> {ok, A} = inet:parse_address("::1").                                                        
{ok,{0,0,0,0,0,0,0,1}}                            
> epgsql:connect(#{host => A, port => 5432, username => "postgres", password => "postgres"}).
{ok,<0.31251.0>} 
```

but probably will use ipv4 if you'll use hostname and hostname resolves in both ipv4 and ipv6

**Comment by wwhai** [comment]
Thank you,I have resolved problems

**Comment by wwhai** [comment]
> Well, it works already if you'll just pass an IP address:
> 
> ```erlang
> > {ok, A} = inet:parse_address("::1").                                                        
> {ok,{0,0,0,0,0,0,0,1}}                            
> > epgsql:connect(#{host => A, port => 5432, username => "postgres", password => "postgres"}).
> {ok,<0.31251.0>} 
> ```
> 
> but probably will use ipv4 if you'll use hostname and hostname resolves in both ipv4 and ipv6

Thank you,I have resolved problems

**Comment by seriyps** [comment]
Now when #242 is merged, you can force epgsql to connect via ipv6 like this:
```erlang
epgsql:connect(
  #{host => "localhost",
    username => "postgres",
    password => "******",
    database => "postgres",
    tcp_opts => [inet6]}).
```
