### ISSUE TITLE
Tagging a new release

### ISSUE THREAD

**Issue by galdor** [epgsql/epgsql#236]
Is there a plan to tag a new release soon ?

Currently the last stable release (4.4.0) misses support for `application_name` and various other small fixes.

**Comment by seriyps** [comment]
I can do that. Do you have any more PRs planned so we will make sure they will be included in 4.5.0?

**Comment by seriyps** [comment]
I was thinking about publishing a minor tags (and maybe publish to hex.pm as well) on each merge to master, but had no time to work on it.
There is a slowly-going attempt to implement this strategy (or some parts of it) in another Erlang project https://github.com/for-GET/jesse/pull/84

**Comment by galdor** [comment]
I do not have any PR planned right now. However I just realized that since you are using `master` and `develop`, I can just rely on `master`. 

No need for extra work :)
