### ISSUE TITLE
Connecting to AWS with :replication => "database" causes invalid_authorization_specification

### ISSUE THREAD

**Issue by hansonkd** [epgsql/epgsql#241]
If I try to connect to an RDS instance with these connection options:

```elixir
config = %{
      host: ...,
      port: ...,
      username: ...,
      database: ...,
      password: ...,
      replication: "database",
      ssl: true
}
:epgsql.connect(epgsql_config)
```
results in `{:error, :invalid_authorization_specification}`

I have tracked the issue down to this: https://github.com/epgsql/epgsql/blob/devel/src/commands/epgsql_cmd_connect.erl#L65

Changing this line to omit the replication information and just be `{Opts3,` fixes the issue for me and replication works exactly as planned. The only difference is that I am unable to use the statement `CREATE_REPLICATION_SLOT` and instead have to do `SELECT * FROM pg_create_logical_replication_slot(...)`. However `START_REPLICATION` works fine.

The above fix to remove `["replication", 0, Replication, 0]` from the connection string seems wrong, but it was the only way I could get epgsql to connect to RDS or Aurora. Has anyone else experienced this issue?

**Comment by seriyps** [comment]
Hi. I honestly have no experience with Amazon's PostgreSQL. Let's keep this open if someone have seen similar issues.

**Comment by hansonkd** [comment]
I'm going to close this because the issue resolved itself when I rebooted the instance.
