### ISSUE TITLE
[redshift] error 42703 / undefined_column

### ISSUE THREAD

**Issue by umgeher** [epgsql/epgsql#247]
hej!

I've a issue connecting to redshift...

```
{{badmatch,{error,{error,error,<<"42703">>,undefined_column,<<"c
olumn \"typarray\" does not exist in pg_type">>,[{file,<<"/home/ec2-user/padb/src/pg/src/backend/parser/parse_expr.c">>}
```

I saw an old and closed issue about it (https://github.com/epgsql/epgsql/issues/73). I need to give some connection's option to get it right or it's a bug/error/issue?

**Comment by seriyps** [comment]
Hey. Could you try to connect with `epgsql:connect(#{..., codecs => []})`? This would prevent epgsql from querying special postgres tables upon connection set-up that do not exist on RedShift (since it's based on old versions of PostgreSQL)

**Comment by umgeher** [comment]
thanks mate!
