### ISSUE TITLE
binary parameters

### ISSUE THREAD

**Issue by densone** [epgsql/epgsql#265]
in libpq turning on binary parameters will enable single round trip.. Is there a way to enable single round trip for prepared statements in epgsql?

**Comment by seriyps** [comment]
Hi. Not sure I understand what do you mean by "binary parameters". Is there som documentation or article about it?

For single round-trip with `epgsql` you'd currently need to either cache the named prepared statements or use `squery`.

**Comment by seriyps** [comment]
And for cached prepared statements I made this experimental command as an excercise some time ago. It works, but it's never been in production https://gist.github.com/seriyps/637bf11e34bf4fc7535de6e46eda4f33

**Comment by densone** [comment]
binary_parameters is a config for libpq . The significance it has is by turning that on in pq, it creates single round trip and allows the use of prepared statements with pg bouncer  using a transaction pool.

**Comment by seriyps** [comment]
I still was not able to find any docs describing how exactly it works.
I believe if you know all the datatypes which your query parameters use, you should be able to execute the query in a single round-trip by sending `epgsqla:parse` (asynchronous) and then fake the `#statement{}` you provide as 2nd argument of `equery` or `prepared_query`. But this is not smth that is natively supported or tested by `epgsql`.

But have a look at my other gist that probably does smth close enough to what you are trying to achieve https://gist.github.com/seriyps/0d72fea5168ee0a1be6b56af7ce30c4f. This command lets you perform query with parameters in a single round-trip, but the cost is that you have to explicitly specify the datatype of the each parameter.

**Comment by densone** [comment]
thanks @seriyps will give it a shot with one of these methods.

**Comment by densone** [comment]
@seriyps this module seems to work great thus far. Thanks so much for the info. 
https://github.com/helium/blockchain-http/tree/adt/eequery
