### ISSUE TITLE
epgsql:parse leaves active statement

### ISSUE THREAD

**Issue by matthias-schoeneich** [epgsql/epgsql#271]
Hi,

I believe `epgsql:parse/N` creates an open transaction/statement - which it should not in my opinion.

# environment
* erlang `Erlang/OTP 24 [erts-12.1.4] `
* epgsql at latest head `7abe38b7df4c7f68ce5533654025ea58a23f7327`
* postgresql `PostgreSQL 14.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit`

all config is plain vanilla-  except postgres `statement_timeout` - thats how i noticed it.

# reproduce

```erlang
2>PID = epgsql:get_backend_pid(C),
2>{ok,Stmt} = epgsql:parse(C,<<"stmt">>,<<"select 1">>,[]),
2>PID.
17953
```
other psql session tells me:
```sql
db=# select state, query from pg_stat_activity where pid = 17953;
 state  |  query   
--------+----------
 active | select 1
(1 row)
```

after statement timeout I get on erlang side
```
3> epgsql:squery(C,"select 2").                                  
{error,{error,error,<<"57014">>,query_canceled,                  
              <<"canceling statement due to statement timeout">>,
              [{file,<<"postgres.c">>},                          
               {line,<<"3299">>},                                
               {routine,<<"ProcessInterrupts">>},                
               {severity,<<"ERROR">>}]}}                         
```
which is correct from postgres point of view as plan/prepare took too long.

# doing the same using psql cli

```sql
db=# select pg_backend_pid(); 
 pg_backend_pid                   
----------------                  
          17972                   
(1 row)                           
                                  
db=# prepare stmt as select 1;
PREPARE                           
```
other psql session tells me:
```sql
db=# select state, query from pg_stat_activity where pid = 17972;
 state |           query           
-------+---------------------------
 idle  | prepare stmt as select 1;
(1 row)
```

note the difference in `state` - `active` vs `idle`

# how to work around
add a sync, like this
```erlang
2> PID = epgsql:get_backend_pid(C),
2> {ok,Stmt} = epgsql:parse(C,<<"stmt">>,<<"select 1">>,[]),
2> ok = epgsql:sync(C),
2> PID.                                                     
17990                                                       
```
other psql session tells me:
```sql
db=# select state, query from pg_stat_activity where pid = 17990;
 state |  query   
-------+----------
 idle  | select 1
(1 row)
```

so after sync we are not `active` anymore but idle, so `statement_timeout` does not catch us.

I am neither an expert in postgres fe/be protocol nor in epgsql pluggable commands and yes it is easy to work around... but it feels wrong anyway.

as the same pluggable comand `epgsql_cmd_parse` is used in `epgsql`,`epgsqli` and `epgsqla` - the issue must be in `epgsql_cmd_parse`. btw: the same happens using a 3.x version of epgsql - so it is not an issue that was introduced by adding pluggable commands.

thank you for your support
Matthias

**Comment by seriyps** [comment]
Hi,

first of all, `PREPARE stmt AS SELECT 1` is not the same as `epgsql:parse(C,<<"stmt">>,<<"select 1">>,[])`. 1st one is executed by `psql` using "simple query protocol" (similar to `epgsql:squery`), while `epgsql:parse` executes a 1st step of 3-step (parse-bind-execute) "extended query protocol". So I'd say it's incorrect to compare them.

Regarding the trick with `epgsql:sync` and troubles with `statement_timeout` - it's interesting! I didn't know this happens. But I'm not sure we should really add `sync` to be executed automatically by `parse`, because it would create additional traffic for the usecases not relying on statement timeouts. I can suggest you to either create your own pluggable command for that, or to use `epgsqla:parse + epgsqla:sync` (send `sync` before the response to `parse` is received - to avoid double-roundtrips).

Also, I don't think `parse` opens a transaction: https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-PG-STAT-ACTIVITY-VIEW

> state text
> Current overall state of this backend. Possible values are:
>     active: The backend is executing a query.
>     idle: The backend is waiting for a new client command.
>     idle in transaction: The backend is in a transaction, but is not currently executing a query.
>     idle in transaction (aborted): This state is similar to idle in transaction, except one of the statements in the transaction caused an error.
>     fastpath function call: The backend is executing a fast-path function.
>     disabled: This state is reported if [track_activities](https://www.postgresql.org/docs/current/runtime-config-statistics.html#GUC-TRACK-ACTIVITIES) is disabled in this backend.

**Comment by matthias-schoeneich** [comment]
Hi,

you are correct. Its not a transaction it is an active statement - i changed the name of this issue to reflect that.

For now I will go the `epgsqla` way as you suggested - for pluggable commands I need to learn a bit more.

Thank you
