### ISSUE TITLE
Lack of logging on transaction rollback

### ISSUE THREAD

**Issue by quiquepaz** [epgsql/epgsql#29]
Hi,

I've been using epgsql for a month or so and so far I'm quite pleased with it. However, there is one thing I miss: a log message when a transaction crashes. There is a `TODO` note in https://github.com/epgsql/epgsql/blob/master/src/pgsql.erl#L207 , so I'm sure you've thought about this more than I have ;)

What about just adding a call to `error_logger:error_report([{transaction_aborted, Why}])`? error_logger is always present, and for those using `lager` the message can be automatically picked up.

**Comment by seriyps** [comment]
Fixed by #147
