### ISSUE TITLE
How to run system commands? Like \d or \l

### ISSUE THREAD

**Issue by Dryymoon** [epgsql/epgsql#31]
I was trying very many methods for run system commands, but unsuccessfully.
Is any method to run this commands?

**Comment by davidw** [comment]
Closing after no further comments.

**Comment by Dryymoon** [comment]
Thanks very mutch for answer, very helped me.

**Comment by davidw** [comment]
@Dryymoon no problem, glad it helped.  If you think there's a good case to be made for including these, in some way, I'm happy to hear it.
