### ISSUE TITLE
Support connection without database

### ISSUE THREAD

**Issue by ddeboer** [epgsql/epgsql#44]
If no database exists with the same name as the user, `pgsql:connect("localhost", "some_user", "pass", [])` will throw:

``` erlang
{error,{error,fatal,<<"3D000">>,
              <<"database \"some_user\" does not exist">>,[]}}
```

Would it be possible to support connections that don’t select a database right away? Perhaps by passing `undefined` to `database` in `Opts`, like this:

``` erlang
pgsql:connect("localhost", "some_user", "pass", [{database, undefined}]).
```

**Comment by seriyps** [comment]
This one actualy supported starting from 65002570.
It uses `postgres` database by-default then.

```erlang
{ok, C1} = epgsql:connect(#{host => "localhost", port => 5432, username => "postgres", password => "postgres"}).                           
{ok,<0.159.0>}
13> epgsql:squery(C1, "SELECT current_database()").
{ok,[{column,<<"current_database">>,name,64,-1,0}],
    [{<<"postgres">>}]}
```
