### ISSUE TITLE
Add travis.ci support

### ISSUE THREAD

**Issue by seriyps** [epgsql/epgsql#50]
Now, when we can setup and run tests fully automatically, it's good time to add CI support.

You may use, say, https://github.com/sfackler/rust-postgres/blob/master/.travis.yml as a reference.

Travis docs about postgresql setup: http://docs.travis-ci.com/user/using-postgresql/ (but we can just use our existing tests setup mechanism)

**Comment by davidw** [comment]
Hrm; I wonder if that works out ok with the custom pg_hba.conf file we need?

**Comment by seriyps** [comment]
@davidw see https://github.com/sfackler/rust-postgres/blob/master/.travis/setup.sh

**Comment by seriyps** [comment]
@davidw but that example uses system postgresql. We can launch own instance, reusing existing test infrastructure.

**Comment by davidw** [comment]
I'm happy to include this, but I'm afraid I'll probably need some help to get it off the ground.

**Comment by seriyps** [comment]
Fixed by #53
