### ISSUE TITLE
Error in data conversion

### ISSUE THREAD

**Issue by kpy3** [epgsql/epgsql#60]
Hello,

I've found unexpected behaviour in timestamp conversion:

```
2> epgsql:equery(C1, "select * from test").
{ok,[{column,<<"test">>,timestamp,8,-1,1}],
    [{{{2015,3,2},{19,14,1.4729999999999999}}}]}
3> epgsql:squery(C1, "select * from test").
{ok,[{column,<<"test">>,timestamp,8,-1,0}],
    [{<<"2015-03-02 19:14:01.473">>}]}
```

So I expect 1.473 first query, but see something different, possibly convert to float error.

**Comment by davidw** [comment]
What does Postgres actually send in the first case?

**Comment by seriyps** [comment]
Looks like epgsql just converts seconds to float.
https://github.com/epgsql/epgsql/blob/master/src/epgsql_fdatetime.erl#L73-L75

So, this is just float precision issue. Not sure if that can be fixed at all.

**Comment by seriyps** [comment]
You may round it manualy:
```erlang
1> round(1.4729999999999999 * 1000) / 1000.0.
1.473
```

**Comment by kpy3** [comment]
Yes, but result seems to be calendar:datetime() (at last for me) with broken contract, which is not suitable for timestamp. May be erlang:timestamp() is better for passing timestamp from PostgreSQL?

**Comment by davidw** [comment]
@kpy3 it's been that way for a while, so I think it's probably not a great idea to change it at this point.

**Comment by davidw** [comment]
I am closing this because most existing code expects this format, for better or worse.  Changing it would lead to big incompatibilities.

I'd be happy to add a helper function that goes from pg_datetime() to erlang:datetime()

**Comment by seriyps** [comment]
Maybe this issue about typespec violation https://github.com/epgsql/epgsql/blob/master/src/epgsql.erl#L51-L52 ?

**Comment by davidw** [comment]
@seriyps good catch; yes I think we should change that spec to match what actually gets output.
