### ISSUE TITLE
Redshift Support

### ISSUE THREAD

**Issue by edhollandAL** [epgsql/epgsql#73]
Hi, 

Is it an aim of this project to provide support for the AWS redshift product? Redshift is a heavily modified (most of the API is untouched) version of postgres 8.0.2. 

The current master fails with redshift as it expects the format of the `pg_type` to be that of 9.x releases of redshift.  https://github.com/epgsql/epgsql/blob/master/src/epgsql.erl#L106-L112

As the datatypes setup with this function are not available in AWS redshift there is no harm from the Redshift perspective in just failing to configure the cache, however this may cause unexpected edge cases for other users.

Please advise if you would be willing to accept patches to enable support for redshift

Thanks

Ed

**Comment by davidw** [comment]
Is there any reason to *not* accept patches to support redshift?  Will it create problems or incompatibilities with 'regular' Postgres?

**Comment by edhollandAL** [comment]
@davidw: redshift is based on postgres 8.0.2, which is quite a lot older than current postgres stable.
 
I believe for most cases this should cause very little problems, as the postgres API seems pretty stable. However in places where we introspect the internals of postgres (such as  https://github.com/epgsql/epgsql/blob/master/src/epgsql.erl#L106-L112) there is much more likely to be conflicts.

The current master fails to connect to a RS instance with the following exception
```
3> epgsql:connect("notarealhostredshift.amazonaws.com", "notarealuser", "FaK3pass", [{database, "dev"}, {port, 5439}]).
** exception error: no match of right hand side value {error,{error,error,<<"42703">>,
                                                                    <<"column \"typarray\" does not exist in pg_type">>,[]}}
     in function  epgsql:update_type_cache/1 (src/epgsql.erl, line 111)
     in call from epgsql:connect/5 (src/epgsql.erl, line 99)
```
a quick and dirty 'fix' would be something like
```
diff --git a/src/epgsql.erl b/src/epgsql.erl
index eff103e..d368031 100644
--- a/src/epgsql.erl
+++ b/src/epgsql.erl
@@ -109,8 +109,14 @@ update_type_cache(C) ->
     Query = "SELECT typname, oid::int4, typarray::int4"
             " FROM pg_type"
             " WHERE typname = ANY($1::varchar[])",
-    {ok, _, TypeInfos} = equery(C, Query, [DynamicTypes]),
-    ok = gen_server:call(C, {update_type_cache, TypeInfos}).
+    case equery(C, Query, [DynamicTypes]) of
+        {ok, _, TypeInfos} ->
+            ok = gen_server:call(C, {update_type_cache, TypeInfos});
+        {error, _Error} ->
+            %% Do not fail connect if we cant update the cache,
+            %% as this can occur for old postgres version (ie AWS redshift)
+            ok
+    end.
```

I wanted to confirm a desire to be able to support redshift before looking for a 'nicer' approach (suggestions welcomed!)

**Comment by seriyps** [comment]
I guess it's resolved? We have this fix in master.

**Comment by edholland** [comment]
@seriyps: yes, please close this issue :)
