### ISSUE TITLE
Publish package in hex.pm

### ISSUE THREAD

**Issue by jcomellas** [epgsql/epgsql#75]
It would be very useful for `epgsql` to be available as a package for `rebar3` in [hex.pm](http://hex.pm/). I could upload it, but I think it would be better for someone with commit access to the repository to do so.

The instructions are [here](https://hex.pm/docs/rebar3_publish).

**Comment by davidw** [comment]
@jcomellas I'm happy for you to upload it if you'd be willing to track both epgsql and the hex package.

**Comment by jcomellas** [comment]
@davidw OK, I will publish the package then. I'll close the ticket when it's done.

**Comment by jcomellas** [comment]
I have already pushed the package to hex.pm. I'll push a PR later with some changes to the .app file to add a bit more information to the package information in the hex.pm page.

**Comment by davidw** [comment]
Thank you, @jcomellas !
